# syobon-go configuration file
# Edit this file to change game settings.

[controls]
left = ["left"]
right = ["right"]
jump = ["z", "up"]
double_speed = ["space"]
self_destruct = ["0"]
exit = ["escape"]
return_to_title = ["f1"]
fullscreen = ["f11"]

[audio]
mute = false
master_volume = 1.0 # Range: 0.0 - 1.0; see https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2/audio#Player.Volume
sample_rate = 44100 # Sample rate for audio playback; see https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2/audio#NewContext

[graphics]
fullscreen = false
vsync = true
enable_fps_counter = true
